name: ${project.name}
main: com.projectg.geyserupdater.spigot.SpigotUpdater
version: ${project.version}
depend: [Geyser-Spigot]
description: 自动或手动下载新的 Geyser 版本并在服务器重启时应用。
api-version: 1.13

commands:
  geyserupdate:
    description: 更新 Geyser 的命令
    permission: gupdater.geyserupdate
    aliases: /geyserupdate
